### ISSUE TITLE
Is there any way for the process not to prompt the user?

### ISSUE THREAD

**Issue by asdf01** [parse-server-modules/parse-files-utils#18]
Hey Guys

Is there any way for the util not to prompt the user we when try to run it so that it can be run as part of a script?  Currently, the following prompt appears:
`About to start the file transfer. Does the above look correct?`

e.g. is there any environment variable we can setup or parameter we can pass to it?  Thanks.

**Comment by flovilmart** [comment]
For now it's only a command line tool.

**Comment by asdf01** [comment]
Hi @flovilmart.  Thanks.
