### ISSUE TITLE
Error migration file to S3.

### ISSUE THREAD

**Issue by kevinlee85** [parse-server-modules/parse-files-utils#19]
I am not sure what's the problem, below is my error log:

14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid parse-files-utils@0.0.1
16 verbose cwd /b01_backend/parse/parse-files-utils
17 error Darwin 15.6.0
18 error argv "/usr/local/Cellar/node/6.6.0/bin/node" "/usr/local/bin/npm" "start" "config.js"
19 error node v6.6.0
20 error npm  v3.10.7
21 error code ELIFECYCLE
22 error parse-files-utils@0.0.1 start: `node index.js "config.js"`
22 error Exit status 1
23 error Failed at the parse-files-utils@0.0.1 start script 'node index.js "config.js"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the parse-files-utils package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index.js "config.js"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs parse-files-utils
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls parse-files-utils
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by acinader** [comment]
there's insufficient info here and its ver old.  going to close.   if this is still an issue, please re-open.
