### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by sylvioleblanc** [parse-server-modules/parse-files-utils#23]
I'm testing out these scripts and for some reason it seems like they are missing from of my files.  I'm getting some of the files, just not all of them.

To my understanding, these scripts are suppose to find all the PF FILES... correct?

Is there something that I need to configure other than the config file?
Is there a verbose option which I can enable to see more details about what the scripts are doing?

Here is the content of my config file....

Thanks in advance!

var FileAdapter = require('parse-server-fs-adapter');
var S3Adapter = require('parse-server-s3-adapter');
var GCSAdapter = require('parse-server-gcs-adapter');

module.exports = {
  applicationId: “xxx”,
  masterKey: “xxx”,
  mongoURL: "mongodb://<username>:<password>@mongourl.com:27017/database_name",
  serverURL: "https://api.parse.com/1",
  filesToTransfer: 'all',
  renameInDatabase: false,
 // transferTo: 'filesystem',
  transferTo: 'filesystem',

  // For filesystem configuration
  filesystemPath: './downloaded_files',

  // For S3 configuration
  aws_accessKeyId: "ACCESS_KEY_ID",
  aws_secretAccessKey: "SECRET_ACCESS_KEY",
  aws_bucket: "BUCKET_NAME",
  aws_bucketPrefix: "",

  // For GCS configuration
  gcs_projectId: "GCS_PROJECT_ID",
  gcs_keyFilename: "credentials.json",
  gcs_bucket: "BUCKET_NAME",

  // Or set filesAdapter to a Parse Server file adapter
  // filesAdapter: new FileAdapter({
  //  filesSubDirectory: './downloaded_files'
  // }),
  // filesAdapter: new S3Adapter({
  //   accessKey: 'ACCESS_KEY_ID',
  //   secretKey: 'SECRET_ACCESS_KEY',
  //   bucket: 'BUCKET_NAME'
  // }),
  // filesAdapter: new GCSAdapter({
  //   projectId: "GCS_PROJECT_ID",
  //   keyFilename: "credentials.json",
  //   bucket: "BUCKET_NAME",
  // }),
};

**Comment by andresteves** [comment]
@sylvioleblanc I have a similar problem. I was able to copy all the files using that script but still parse says 'File not found' when I try to see them

Were you able to solve your problem?
