### ISSUE TITLE
Actual file transfer to MongoDB

### ISSUE THREAD

**Issue by ilyashev** [parse-server-modules/parse-files-utils#26]
My understanding is that this tool is supposed to help migrate my files from parse to my own mongoDB instance. However, all it appears to let me do is download the files to my local machine. I don't want to use S3 or GCS, but to host the files in mongo for now. How does this tool help me get those files to the mongoDB that my parse server is talking to?

**Comment by kalitas** [comment]
it is not. its only let you migrate your files to other hosting service such as s3 or to your local machine.

**Comment by chsriman** [comment]
So, how do we actually migrate the files to the Mongo DB?

**Comment by acinader** [comment]
this question is outside the scope of this migrate script.
