### ISSUE TITLE
S3 file permissions open to the internet

### ISSUE THREAD

**Issue by asdf01** [parse-server-modules/parse-files-utils#27]
Hey Guys

Thanks for making a nice and easy to use tool.  

I noticed that the files transferred over by the tool has really permissive permissions in S3.  Anyone on the internet can basically access it if they know the url.  

Is this how they were in the Parse.com managed s3 account?  Or is the tool giving those files those "Everyone" permissions when it transfers those files over?

Do they need to be that open for parse-server to work?

Thanks

**Comment by flovilmart** [comment]
Yes, this is how it was on Parse.com, and yes we need that so the files are all accessible to the clients.
