### ISSUE TITLE
what should be flow to migrate files

### ISSUE THREAD

**Issue by sagarmusale8** [parse-server-modules/parse-files-utils#28]
Hi,

I would like to know the flow to migrate parse files to s3 buckets. Mainly after finalize the migration of DB or before that?

I tried to migrate before finalize but it was not giving option to finalize. Please help me out here.

**Comment by kalitas** [comment]
its does not matter, if you migrate before or after you finalize the migration process. parse is hosting your files even after you finalize the migration process.
