### ISSUE TITLE
How do I tell my parse server or parse dashboard to get the images from s3 and not from parse anymore?

### ISSUE THREAD

**Issue by kalitas** [parse-server-modules/parse-files-utils#30]
I transfered my files from hosted parse.com to s3 bucket on aws using this utility. i kept the name of the files. now I would like that my parse server would take the files from my new s3 bucket and not from the original parse.com

i did remove the file key from my app settings as read in the above utility.
i init parse server with the s3 adapter:

filesAdapter: new S3Adapter( process.env.AWS_ACCESS_KEY_ID || "xxxx", process.env.AWS_SECRET_ACCESS_KEY || "xxx/xxx/xxx", process.env.BUCKET_NAME ),
when uploading new files - everything is ok. its kept on the s3 and i can see it in my apps
the only problem is with the old files. or to be more specific is with the base url:its not my s3 but parse.com

**Comment by kalitas** [comment]
@acinader, do you know the answer?

**Comment by kalitas** [comment]
someone?

**Comment by mlauwers-edentify** [comment]
I think that Parse Server will use the file adapter if the filename does not match any of the valid Parse filenames (thus does not start with tfss or match the Parse legacy file regex).

**Comment by apersaud** [comment]
To do this you need to also set the `baseUrl` property to the bucket url path (ex. `https://yourbucket.s3.amazonaws.com/`....) - make sure you include the ending `/`.

Here is an example configuration:
```javascript
var env = process.env;
filesAdapter = new S3Adapter(
    env.S3_ACCESS_KEY,
    env.S3_SECRET_KEY,
    env.S3_BUCKET, {
      region: 'us-east-1',
      directAccess: true,
      bucketPrefix: env.S3_BUCKET_PREFIX,
      baseUrl: env.S3_BASE_URL // <--- THIS PROPERTY
    }
  );
```

From there, make sure your open source Parse Server is no longer using the `fileKey` parameter. From there your Parse dashboard (when using the open-source version with your open-source server) will always get the file from your S3 bucket. The hosted platform will always return the hosted file.

**Comment by gopalesagar** [comment]
For me it worked **without** the "/" in the end of the baseUrl. I was getting double forward slash in the file URLs and were not getting rendered.

**Comment by kalitas** [comment]
I will try and let you know please dont close yet

**Comment by JunJia** [comment]
If you noticed, the file names generated by self-hosted and parse-hosted are different. Parse-hosted generates file names with prefix 'tfss'. I believe this is the way how parse sdk indicate where the file store.

**Comment by acinader** [comment]
@kalitas go ahead and re-open if this is still an issue.
