### ISSUE TITLE
Getting "Failed request (403) " , when trying to migrate legacy files to S3 or storing files into file system

### ISSUE THREAD

**Issue by asif13** [parse-server-modules/parse-files-utils#31]
Initializing transfer configuration...
Initializing s3 adapter
Fetching schema...
Fetching all objects with files...
Processing 5 files
Saving files with s3
Failed request (403) skipping: http://files.parse.com/*******/****.jpg

**Comment by woodardj** [comment]
I'm no expert, and I haven't run this file util yet, but if I had to guess, your AWS/S3 credentials are either incorrect, or not set with the proper permissions.

**Comment by mlauwers-edentify** [comment]
Is the file directly accessible (to test by pasting the url in a browser)? Since a few days many of my Parse file URLs are returning a 403 as well.

**Comment by teehamaral** [comment]
If you are using the second option, you must to remove fileKey of the parse server configuration. If you keep it, the path should be directed to parse.com server files.
