### ISSUE TITLE
S3 File Transfer Timeout 

### ISSUE THREAD

**Issue by TahiG** [parse-server-modules/parse-files-utils#34]
Hi,

I'm getting a timeout error when transferring all my parse.com hosted files to S3. Please advise?

![screenshot 2016-12-04 17 51 56](https://cloud.githubusercontent.com/assets/22755405/20868093/fe51bbfc-ba4a-11e6-9285-59e9c8b44856.png)

**Comment by SatishMotif** [comment]
@TahiG i am also facing the same issue.
Can anyone from parse reply here?

**Comment by TahiG** [comment]
Hi SatishMotif,

I realised that even though the terminal gave an error, the files had actually been transferred. Hope it's the same for you.

**Comment by teehamaral** [comment]
The same issue happened with me. What's the solution?

**Comment by teehamaral** [comment]
I resolved this issue updating the time directly in the aws-sdk installed (`parse-files-utils/node_modules/aws-sdk/lib/config.js`): https://github.com/aws/aws-sdk-js/blob/7c3760780a23eed98548261cc8245b3d1d260e40/lib/config.js#L461

**Comment by SatishMotif** [comment]
@teehamaral What if I am transferring my files to azure storage account? can you tell me that where should I increase time limit?

**Comment by teehamaral** [comment]
Hey @SatishMotif, could you paste your error log here?

**Comment by SatishMotif** [comment]
here it is:
<img width="638" alt="screen shot 2017-01-17 at 4 25 06 pm" src="https://cloud.githubusercontent.com/assets/16287244/22019024/b277cbf4-dcd7-11e6-9eab-2584bd356620.png">

**Comment by teehamaral** [comment]
Maybe you need follow the path: `parse-files-utils/node_modules/azure-storage/node_modules/request/request.js` and change the logic on line 751, maybe set the integer number instead check if `self.timeout` exists.

**Comment by SatishMotif** [comment]
Thank you very much  @teehamaral 
Can you tell me the exact code which should put there, As i am totally unaware with js.

**Comment by teehamaral** [comment]
I think that you can change `var timeout = self.timeout < 0 ? 0 : self.timeout` to `var timeout = 300000` or set `self.timeout = 300000;` in the `function Request(options){}`
