### ISSUE TITLE
Feature request: support array of ParseFiles in a field

### ISSUE THREAD

**Issue by gorillatapstudio** [parse-server-modules/parse-files-utils#35]
I have a schema with a field that stores an array of images shown as below. From the index.js of the file utils, it looks like the migration tool will not migrate this kind of files. Is it possible to add this feature to the tool? I think it is pretty common to store an array of images for a post using parse.

(array of ParseFile)

[{"__type":"File","name":"tfss-aedd415b-ccbe-4e9b-ace1-2def56abfe90-file","url":"http://files.parsetfss.com/6c3d5bc8-0d99-49d1-85a5-e3fd477ada9b/tfss-aedd415b-ccbe-4e9b-ace1-2def56abfe90-file"},
{"__type":"File","name":"tfss-4a8b56a1-24ce-449a-baaa-7f697995d721-file","url":"http://files.parsetfss.com/6c3d5bc8-0d99-49d1-85a5-e3fd477ada9b/tfss-4a8b56a1-24ce-449a-baaa-7f697995d721-file"},
{"__type":"File","name":"tfss-d3aded4a-c4bd-40ac-bcd7-3cf004ec3573-file","url":"http://files.parsetfss.com/6c3d5bc8-0d99-49d1-85a5-e3fd477ada9b/tfss-d3aded4a-c4bd-40ac-bcd7-3cf004ec3573-file"}]

**Comment by flovilmart** [comment]
I'll look into it. Also nested files in objects would be nice.

**Comment by gorillatapstudio** [comment]
Great!

**Comment by krushnaal-pai** [comment]
Hi @flovilmart ..
Is this array problem resolved? ..I tried the util today and found that all my array fields are unchanged.
I have thousands of images lying in array fields that need to be transferred to s3. We are nearing the deadline, please help because I'm not a pro and I'm completely dependent on this util for the transfer.

**Comment by flovilmart** [comment]
I havent't had the time to look at it as my full time job is taking me a lot of energy lately. I'll try to do my best to reach some solution.

**Comment by krushnaal-pai** [comment]
@flovilmart  Thanks a lot ... I appreciate all the work you've been doing for this repo.

**Comment by rbarriuso** [comment]
@flovilmart Do you think this can be fixed before the Parse.com server shutdown tomorrow? Thanks in advance.

**Comment by flovilmart** [comment]
À PR has been open by @codebreach, I'll review shortly.

**Comment by rbarriuso** [comment]
We've created a fork which did the job: https://github.com/TribalyteTechnologies/parse-files-utils
