### ISSUE TITLE
Failed request (403) skipping

### ISSUE THREAD

**Issue by rusmichal** [parse-server-modules/parse-files-utils#38]
Hello 

I am migrating parse file to AWS S3 but I got 403 and I cannot resolve that problem. What I did:

1. I created new user `Test-man` with that [configuration](https://github.com/ParsePlatform/parse-server/wiki/Configuring-File-Adapters#set-up-your-bucket-and-permissions)
2. Policy for `Test-man`:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:ListAllMyBuckets",
            "Resource": "arn:aws:s3:::*"
        },
        {
            "Sid": "Stmt1482487207469",
            "Action": "s3:*",
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::Test/*"
        }
    ]
}
```

3. I created  new bucket `Test` and set permission for everyone:
![zrzut ekranu 2016-12-23 o 11 54 16](https://cloud.githubusercontent.com/assets/15652344/21452371/a4b88b32-c906-11e6-8590-7b97f3d9947c.png)

**config.js file**
```
var FileAdapter = require('parse-server-fs-adapter');
var S3Adapter = require('parse-server-s3-adapter');
var GCSAdapter = require('parse-server-gcs-adapter');

module.exports = {
  applicationId: "my api id #####",
  masterKey: "my master key #####",
  mongoURL: "url mongodb #####",
  serverURL: "server url ######",
  filesToTransfer: 'parseOnly',
  renameInDatabase: false,
  transferTo: 'filesystem',

  // For filesystem configuration
  filesystemPath: './downloaded_files',

  // For S3 configuration
  aws_accessKeyId: "Test-man access key",
  aws_secretAccessKey: "Test-man secret access key,
  aws_bucket: "Test,
  aws_bucketPrefix: "",

   filesAdapter: new S3Adapter({
     accessKey: "Test-man access key",
     secretKey: "Test-man secret access key,
     bucket: 'Test',
     region: 'us-west-2',
     bucketPrefix: ''
   })
};

```
I got that results:
```
Initializing transfer configuration...
Initializing filesystem adapter
Fetching schema...
Fetching all objects with files...
Processing 33026 files
Saving files with filesystem
Failed request (403) skipping: https://s3_bucket.s3.amazonaws.com/tfss-ee109f15-9a91-4580-af0d-79b41168f0d1-file
...
```
When I have logged in Test-man account I saw Test bucket and I can open it and upload images manually.

Any idea What I am doing wrong?

**Comment by sachinhegde** [comment]
I'm running into a similar issue. I am migrating my files from parse to S3. I also get errors like -
Failed request (403) skipping: http://files.parsetfss.com/f4c8f750eecd2b5af9a293492c72b719bab497dd/tfss-b167a835-fc53-44ed-80d8-93d8fb8bda2a-69162D9C-CB51-471E-BA33-FBB698FA10A2.JPG

Did you find a fix for this?

**Comment by logix007** [comment]
file does not actually exist.

**Comment by davimacedo** [comment]
Check if your file key in parse server is exactly the same you have in parse.com. Otherwise, parse server s3 adapter will generate wrong urls for the files and the migration tool will not be able to load them.

**Comment by sachinhegde** [comment]
Thanks David, there was an issue with the file_key & parse server. Fixing that resolved the issue for me.

**Comment by KBog** [comment]
Same issue here, I can see the files in my S3 bucket with proper meta after running the migration tool, but it failed updating the file urls:
```
Failed request (403) skipping: http://files.parsetfss.com/...
Failed request (403) skipping: http://files.parsetfss.com/...
```

So hovering on the files in my dashboard still shows `files.parsetfss.com/...`

I have checked the file key in my parse server on AWS env config, matches the one on parse.com.

**Comment by rusmichal** [comment]
Hey guys, I have added fileKey to parse-server configuration file and it works

**Comment by spiderguy84** [comment]
I have a similar issue, but I've went through all these trouble-shooting steps already.  My issue is slightly different in that instead of  `skipping: http://files.parsetfss` it shows `skipping: https://fritchdirectory.s3.amazonaws.com/tfss`

**Comment by rusmichal** [comment]
This is my configuration, it works well, I can stop transfer and start again with skipping files that already has been transferred.

```
var S3Adapter = require('parse-server-s3-adapter');

module.exports = {
  applicationId: "parseApiId",
  masterKey: "parseMasterKey",
  mongoURL: "mongodb url",
  serverURL: "serverURL",
  filesToTransfer: 'parseOnly',
  renameInDatabase: true,
  renameFiles: true,
  transferTo: 'filesystem',

  // For S3 configuration
  aws_accessKeyId: "awsKey",
  aws_secretAccessKey: "awsSecretKey",
  aws_bucket: "bucket-files",
  aws_bucketPrefix: "subdirectory/",

   filesAdapter: new S3Adapter({
     accessKey: "awsKey",
     secretKey: "awsSecretKey",
     bucket: 'bucket-files',
     region: 'us-west-2',
     bucketPrefix: 'subdirectory/'
   });
``
