### ISSUE TITLE
Unable to fetch files with https links(http works fine)

### ISSUE THREAD

**Issue by ShamimEmon** [parse-server-modules/parse-files-utils#39]
I am trying to migrate files from parse server to our own s3 bucket.Files whose download links are https are not fetched at all.However,with same configuration it works fine for files with http links.

Here is my config.js details:
`var S3Adapter = require('parse-server-s3-adapter');

module.exports = {
  applicationId: “xxxx”,
  masterKey: "xxxx",
  mongoURL: "xxxx",
  serverURL: "https://api.parse.com/1",
  filesToTransfer: 'parseOnly',
  renameInDatabase: true,
  transferTo: 'S3',

 
  //For S3 configuration
  aws_accessKeyId: "xxxx",
  aws_secretAccessKey: "xxxx",
  aws_bucket: "xxxx",
  aws_bucketPrefix: "",

   s3Adapter: new S3Adapter({
     accessKey: "xxxx",
     secretKey: "xxxx",
     bucket: 'xxxx',
     directAccess: true,
     bucketPrefix: ''
   })
};
`
and in case of https files here is the output : 

Initializing transfer configuration...
Connecting to MongoDB
Successfully connected to MongoDB
Initializing s3 adapter
Fetching schema...
Fetching all objects with files...
Processing 0 files
Saving files with s3
Complete!

How should I resolve this issue?Any help would much appricated

**Comment by MateusCarvalho** [comment]
Hi @ShamimEmon, the Server Url is your new Parse Server ex: (http://myparseserver.com/parse)

**Comment by chuninator** [comment]
@ShamimEmon running into the same problem... Any solution? When I pass in my serverURL, I get `{"error":"unauthorized"}`
