### ISSUE TITLE
Error after fetching schema

### ISSUE THREAD

**Issue by acinader** [parse-server-modules/parse-files-utils#4]
Actively debugging now, but here's what I get:

```
Initializing transfer configuration...
Connecting to MongoDB
Successfully connected to MongoDB
Initializing s3 adapter
Fetching schema...
{"code":103,"error":"Invalid classname: _PushStatus, classnames can only have alphanumeric characters and _, and must start with an alpha character "}
```

my config (with redacted stuff):

```
{
  "applicationId": "",
  "masterKey": "",
  "mongoURL": "",
  "serverURL": "https://api.parse.com/1",
  "filesToTransfer": "parseOnly",
  "renameInDatabase": true,
  "transferTo": "s3",
  "filesystemPath": "./downloaded_files",
  "aws_accessKeyId": "",
  "aws_secretAccessKey": "",
  "aws_bucket": ""
}
```

**Comment by flovilmart** [comment]
ok, go to your DB and delete the _PushStatus from the _SCHEMA table, it should not be there in the 1st place but for some reason it's there.

**Comment by acinader** [comment]
```
commit bae19f2c7698063ad0d67b3e26072827e0799f93
Author: Florent Vilmart <flovilmart@users.noreply.github.com>
Date:   Mon Jul 18 11:51:50 2016 -0400
```

**Comment by acinader** [comment]
ok, that fixed it.  thanks.

**Comment by flovilmart** [comment]
see https://github.com/ParsePlatform/parse-server/issues/2275 for your error, we're trying to track it down but that's quite complex

**Comment by flovilmart** [comment]
@acinader be careful out there, you should not run it with anything in production yet

**Comment by acinader** [comment]
thanks @flovilmart.  

I have a dev version of our app on parse.com and I am using a backup db (dev db) on mlab.  

If I've got it right, there's no way that the images are being touched on s3, so I should be ok.

**Comment by acinader** [comment]
and thanks for the concern @flovilmart.  much appreciated!

**Comment by flovilmart** [comment]
yep, thanks for the commitment to make this happen, you guys are awesome!
