### ISSUE TITLE
ETIMEDOUT while migrating to S3

### ISSUE THREAD

**Issue by sachinhegde** [parse-server-modules/parse-files-utils#40]
I'm trying to migrate my files from the parse server to S3. (Around 14,000 files) But after 5000 or so I hit the error - 
{ [Error: connect ETIMEDOUT 54.230.48.113:80]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '54.230.48.113',
  port: 80 }

Note that I am on the free tier on parse. Is this some kind of timeout due to limited resources?

**Comment by tgmcguire** [comment]
I just ran into this issue as well. File size and connection speed may be a factor here. See [here](https://github.com/parse-server-modules/parse-files-utils/issues/34#issuecomment-270006900) – the migration process seemed to begin working for me after updating this timeout to something longer (like 500000ms).
