### ISSUE TITLE
Image files nowhere to be found

### ISSUE THREAD

**Issue by spiderguy84** [parse-server-modules/parse-files-utils#41]
I input everything, my S3 bucket, appid, master key, parse app id, the whole deal.  I told it to move parseOnly rename everything too.  Indeed everything did get renamed in my mongo, but the S3 bucket is still empty, and worse yet, now the images can't even be viewed from Parse.com as I get an access denied message.

**Comment by acinader** [comment]
if this is still an issue, please provide the config you are using.
