### ISSUE TITLE
AWS EC2 for parse-files-utils

### ISSUE THREAD

**Issue by BarryWood34** [parse-server-modules/parse-files-utils#43]
Has anyone used AWS EC2 to install and run this code?

Assuming I have the Params and s3 set up already, is the process...

1. Create an EC2 instance with node.js

2. SSH to it and install following the steps below

Installation

Clone the repo: git clone git@github.com:parse-server-modules/parse-files-utils.git
cd into repo: cd parse-files-utils
Install dependencies: npm install

3. Modify the config.js file accordingly

4. Then run using...  $ npm start config.js

(not been using node.js/npm or javascript for very long)

Looking at ways to speed the process up... Is it possible to provision and execute on 2 or more servers concurrently to speed up the transfer, it looks like the only issue would be when the two scripts catch up with each other they might trigger http failed request/skipping errors when the processes trip over the same data?? or is this not likely?

Is it worth making a 2nd version of the software for a 2nd EC2 instance and 'sort descending' the createdAt for the files fetch query so one process starts at the top and the other starts at the bottom?? - Anyone tried that?

Thanks

**Comment by highelf** [comment]
If you want to increase the speed of process you must create ec2 with more cpus , must of the time spend in lib/index in map and reduce functions for iterate the fetched array before send it to transfer object.

**Comment by highelf** [comment]
If your mongo is powerful enough,  you can increase the amount of limit in query from 1000 to 10000 .

**Comment by BarryWood34** [comment]
OK thank you - how would I "reduce functions for iterate the fetched array before send it to transfer object."

Mongo should cope with 10,000 query limit. - good idea

 - any thoughts on running 2 instances one sorted ascending the other sorted descending on the 'createdAt' field in getObjectsWithFilesFromSchema?

**Comment by acinader** [comment]
#46 is your current issue?
