### ISSUE TITLE
It is not completed

### ISSUE THREAD

**Issue by rusmichal** [parse-server-modules/parse-files-utils#44]
Hello

it looks like my migration is done but it nothing happens for couple of minutes. Take a look

![zrzut ekranu 2017-01-04 o 00 15 55](https://cloud.githubusercontent.com/assets/15652344/21626758/4ccf1e8e-d213-11e6-8c4b-32c2834b38ae.png)

**Comment by acinader** [comment]
press enter.  i think it is just a fluke of the way that progress is printed.  re-open if you files didn't actually transfer (which they should have based on the output.)
