### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by BarryWood34** [parse-server-modules/parse-files-utils#46]
I'm using an AWS r3.2xlarge EC2 instance.  After about 30 minutes of hanging at "Fetching all objects with files..." I'm getting the error below.  I think it's failing whilst building the checks array of objects with files.  Estimated around 2M files...

? About to start the file transfer. Does the above look correct? Yes
Initializing transfer configuration...
Connecting to MongoDB
Successfully connected to MongoDB
Initializing s3 adapter
Fetching schema...
Fetching all objects with files...
    
<--- Last few GCs --->

 1504270 ms: Mark-sweep 1219.9 (1431.9) -> 1213.7 (1432.9) MB, 1594.8 / 0.0 ms [allocation failure] [GC in old space requested].
 1505925 ms: Mark-sweep 1213.7 (1432.9) -> 1213.3 (1434.9) MB, 1654.6 / 0.0 ms [allocation failure] [GC in old space requested].
 1507700 ms: Mark-sweep 1213.3 (1434.9) -> 1221.5 (1403.9) MB, 1775.3 / 0.0 ms [last resort gc].
 1509375 ms: Mark-sweep 1221.5 (1403.9) -> 1230.3 (1403.9) MB, 1674.4 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x603ce8cfb51 <JS Object>
    1: /* anonymous */ [/home/ec2-user/parse-files-utils/lib/index.js:80] [pc=0x3e9fb4794436] (this=0x334f67723949 <a ParsePromise with map 0x2c3d5040ed1>,r=0x32104f80c0d1 <JS Array[1000]>)
    2: wrappedResolvedCallback [/home/ec2-user/parse-files-utils/node_modules/parse/lib/node/ParsePromise.js:153] [pc=0x3e9fb474cbb8] (this=0x334f67723949 <a ParsePromise with map 0x2c3d5040ed1>)
    3: argum...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x109624c [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewUninitializedFixedArray(int) [node]
 6: v8::internal::Factory::NewJSArrayStorage(v8::internal::Handle<v8::internal::JSArray>, int, int, v8::internal::ArrayStorageAllocationMode) [node]
 7: v8::internal::Factory::NewJSArray(v8::internal::ElementsKind, int, int, v8::internal::ArrayStorageAllocationMode, v8::internal::PretenureFlag) [node]
 8: v8::internal::ElementsAccessor::Concat(v8::internal::Isolate*, v8::internal::Arguments*, unsigned int) [node]
 9: 0x9cf139 [node]
10: 0x9f07e8 [node]
11: 0x9f2946 [node]
12: 0x3e9fb40092a7
Aborted

I've tried $npm start config.js --  --max_old_space_size=49152

Any ideas on other things to try?

**Comment by highelf** [comment]
I have 2 suggestions for you
First you can add swap file to increase the capacity of memory 
Second start biggest ec2 instance after your work finished you can terminate it

**Comment by BarryWood34** [comment]
No Matter which size instance I use it fails at the same place even using   --max_old_space_size=4096.  
It's failing inside getAllObjects when the array r hits 513785.  

As it happens in this collection i have 700k documents so if i can cap it at 500k and then run it again but changing the sort by CreatedAt date descending and using less than it might work.  

something like this...

```
function getAllObjects(baseQuery)  {

  var allObjects = [];
  var next = function() {
    if (allObjects.length) {

      baseQuery.lessThan('createdAt', allObjects[allObjects.length-1].createdAt); // <-- changed this line
    }
    return baseQuery.find({useMasterKey: true}).then(function(r){
      allObjects = allObjects.concat(r);
      if (r.length == 0 || r.length > 500000) {   // <-- changed this to stop after 500k objects
        return Promise.resolve(allObjects);
      } else {
        return next();
      }
    });
  }
  return next();
}

function getObjectsWithFilesFromSchema(schema) {
  var query = new Parse.Query(schema.className);
  query.select(schema.fields.concat('createdAt'));
  query.descending('createdAt');  // <-- I've changed this to descending
  query.limit(10000); // < --  I've increased this
  var checks = schema.fields.map(function(field) {
      return new Parse.Query(schema.className).exists(field);
  });
  query._orQuery(checks);

  return getAllObjects(query).then(function(results) {
    return results.reduce(function(current, result){
      return current.concat(
        schema.fields.map(function(field){
          var fName = result.get(field) ? result.get(field).name() : 'DELETE';
          var fUrl = result.get(field) ? result.get(field).url() : 'DELETE';
          return {
            className: schema.className,
            objectId: result.id,
            fieldName: field,
            fileName: fName,
            url: fUrl
          }
        })
      );
    }, []);
  });
}
```


Anyone else had similar issues with this script?

**Comment by acinader** [comment]
@BarryWood34 yes, other people are definitely having this issue.  take a look at https://github.com/parse-server-modules/parse-files-utils/issues/17#issuecomment-269552573

for a proposed solution.  if that works for you, then we should get that change in.  please let me know if it works and if you're willing, submit a pull request with the change (if not, just let me know and I'll make the change)

**Comment by BarryWood34** [comment]
@acinader ok, it turns out I was way overcomplicating it - can't believe I didn't spot it sooner...

All I actually needed to do is add some additional lessThan,greaterThan dates below to break it down into smaller chunks and run several times.  No need to amend the code that's there, except perhaps to add a comment for those with the same problem with large collections...

```
...
function getObjectsWithFilesFromSchema(schema) {
  var query = new Parse.Query(schema.className);
  query.select(schema.fields.concat('createdAt'));
  //  *** OPTIONAL - additional constraints if working with very large collections ***
  // query.greaterThan('createdAt','2011-04-11T00:00:00.0001Z');  // <-- optional 
  // query.lessThan('createdAt','2012-04-11T00:00:00.0001Z');   // <-- optional 
  query.ascending('createdAt'); 
  query.limit(1000);
  var checks = schema.fields.map(function(field) {
      return new Parse.Query(schema.className).exists(field);
  });
```

It might help others.
