### ISSUE TITLE
Socket connection to the server was not read

### ISSUE THREAD

**Issue by MateusCarvalho** [parse-server-modules/parse-files-utils#47]
I needed to change the AWS SDK connection timeout at timeout because the script was not transferring all files. The following message now appears during the migration:
`Your socket connection to the server was not read from or written to within the timeout period.`

**Comment by tgmcguire** [comment]
I just ran into this issue as well. File size and connection speed may be a factor here. See [here](https://github.com/parse-server-modules/parse-files-utils/issues/34#issuecomment-270006900) – the migration process seemed to begin working for me after updating this timeout to something longer (like 500000ms).

**Comment by MateusCarvalho** [comment]
@tgmcguire In my case I put 6000000ms
