### ISSUE TITLE
Skiping transfered files

### ISSUE THREAD

**Issue by rusmichal** [parse-server-modules/parse-files-utils#54]
I have to transfer 80k files. I have transferred 40K files. is it possible to pause process and run it again but without beginning? I want skip files that they have already been transferred.

**Comment by flovilmart** [comment]
I'm afraid it isn't possible at the moment, but I'm not sure. @JeremyPlease ?

**Comment by JeremyPlease** [comment]
Actually, I ran this yesterday with 400k files, ran into some network issues, and had to restart the transfer. It still needed to scan the entire database, but it was able to pick up where it left off because I used these settings:

```
// config.js
module.exports = {
  ...
  filesToTransfer: "parseOnly",
  renameInDatabase: true,
  renameFiles: true,
  ...
};
```

This config updates each file's filename in the database after it is successfully transferred. That way if you run the script again with these options it will skip the already transferred files.

**Comment by rusmichal** [comment]
Ok I will change my config file. So I have already transfered files with config:

```
module.exports = {
  applicationId: "xxx",
  masterKey: "xxxx",
  mongoURL: "xxxxx",
  serverURL: "xxx",
  filesToTransfer: 'parseOnly',
  renameInDatabase: false,
  transferTo: 'filesystem',

  // For filesystem configuration
  filesystemPath: './downloaded_files',
...
}
```
I change to:
```
module.exports = {
  applicationId: "xxx",
  masterKey: "xxx",
  mongoURL: "xxx",
  serverURL: "xxx",
  filesToTransfer: 'xxx',
  renameInDatabase: true,
  renameFiles: true,
  transferTo: 'filesystem',

  // For filesystem configuration
  filesystemPath: './downloaded_files'
...
}
```
Should I remove files which they have already been transfered from Amazon S3?

**Comment by rusmichal** [comment]
It works, but I haven't removed already transfered files

**Comment by JeremyPlease** [comment]
@rusmichal What do you mean by "remove already transferred files"?

There's no need to remove files from parse.com's S3 bucket. Once you transfer the files, Parse Server will no longer access the files on parse.com.

**Comment by rusmichal** [comment]
Weird. Because I ran again script with new configuration from you. It start from begin. I thought that migration process has started from beginning and files are transferring again.
