### ISSUE TITLE
No files are transferred, but no error is there too

### ISSUE THREAD

**Issue by krishnakumarcitrus** [parse-server-modules/parse-files-utils#56]
This is my configuration

> module.exports = {
  applicationId: "xxx",
  masterKey: "xxx",
 mongoURL: "mongodb://localhost:27017/xxx",
  serverURL: "http://172.892.423.342:1337/parse",
  filesToTransfer: 'all',
  renameInDatabase: true,
  transferTo: 'filesystem',
  filesystemPath: './downloaded_files',

And response after running script is 

> Initializing transfer configuration...
Connecting to MongoDB
Successfully connected to MongoDB
Initializing filesystem adapter
Fetching schema...
Fetching all objects with files...
Processing 0 files
Saving files with filesystem
Complete!

Parse server is accessible, mongoDb is authenticated correctly , keys are right. Still nothing did happen and 0 files were processed?

What I expected was all the files which were stored before hosted parse server, will be moved to file in my machine, and its reference in database will be corrected.
Was my expectation right about the file migration script ?

**Comment by flovilmart** [comment]
Are your files stored in proper columns or are they in arrays or nested objects?

**Comment by krishnakumarcitrus** [comment]
They are stored in array.

> [
  {
    "__type": "File",
    "name": "xxxxx_Image.jpg",
    "url": "http://xxx.xxx.xxx:1337/parse/files/xxxxx/xx_Image.jpg"
  },
  {
    "__type": "File",
    "name": "xxxxx_Image.jpg",
    "url": "http://xxx.xxx.xxx:1337/parse/files/xxxxx/xx_Image.jpg"
  }
]

Is this a problem, hope you can tell me a solution for it..

**Comment by flovilmart** [comment]
Yes this is a problem, and we don't have an implementation for this at the moment, see #35.

I need to take some time to look at it or someone else @JeremyPlease or @acinader ?

**Comment by krishnakumarcitrus** [comment]
Okay, please take your time, and please let me confirm certain thinks.

1) When using parse.com server files were stored at MongoDb right? So isn't the files too copied when database was migrated?

2) So when api.parse.com shuts down, the file is still at new hosted server right? That means users can still get it?

**Comment by flovilmart** [comment]
1. no, files were stored on S3, proprietary to parse.com, the files are not copied upon migration
2. no, files are NOT on the new server, you need to migrate them manually.

**Comment by alombard** [comment]
Hi Guys - no pressure on this but wanted to ask if this issue would be resolved prior to the shutdown or if I should plan to do this manually? 

At the moment I have a file as a property inside a custom parse object and although the files were renamed in Mongo - none of the binary objects were created and moved into the files collection. The utility did make a local copy of them on my machine so I can write something to create the objects but wanted to check if necessary prior to doing so.  

Thanks in advance for any help.

Andrew
