### ISSUE TITLE
Skipping 403 Error on S3 Transfer Desperate for Help PLEASE URGENT

### ISSUE THREAD

**Issue by spiderguy84** [parse-server-modules/parse-files-utils#57]
Ok, so I have a Parse.com app I've been working on way too long trying to get migrated. My original Parse class had some file images in it, and I tried using the parse-files-utils tool to move them all over to S3. I did this, but something went wrong in the process and it renamed all the image files on Parse, while not actually moving them to S3. So, I deleted all the images (this is after the mongoDB has already been set up) and re-uploaded files, this time they had different image names. I then set everything up and run the parse-files-utils to upload to S3 and I get this:

I have even edited files in my mLab database with Mongo to make sure that the picture file listed in the database matches what it is searching for here, but to no avail.  I am desperate for help.
```
Initializing transfer configuration...
Connecting to MongoDB
Successfully connected to MongoDB
Initializing s3 adapter
Fetching schema...
Fetching all objects with files...
Processing 41 files
Saving files with s3
Failed request (403) skipping: https://fritchdirectory.s3.amazonaws.com/tfss-1ae62b0d-d71c-415a-838a-51f4fc515085-chisum.jpg
Failed request (403) skipping: https://fritchdirectory.s3.amazonaws.com/tfss-c06d523
```

When I go to the Parse site itself and check on one of those images to download, the filename matches EXACTLY.

**Comment by jigneshk** [comment]
I am having same problem, did you get the solution ?

**Comment by jigneshk** [comment]
I got the problem, It was because of the file-key was wrong in parse server app.

**Comment by SebC99** [comment]
@jigneshk which file-key? the one on your parse-server config? Because there's no file-key in this utils config file, is there?

**Comment by spiderguy84** [comment]
Never did solve anything @jigneshk

**Comment by gabiz** [comment]
@spiderguy84 Looks like your `serverURL` is pointing to your server and it cannot find the files. You may want to try pointing to parse `serverURL:  "https://api.parse.com/1"`
