### ISSUE TITLE
Transfer Files to Gridstore

### ISSUE THREAD

**Issue by GGross5213** [parse-server-modules/parse-files-utils#61]
Is there no way to transfer files to MongoDB Gridstore?

**Comment by andresteves** [comment]
Also would like to know how to do that because I migrate files to server but Parse server does not seem to pick them up.

**Comment by gabiz** [comment]
Looks like GridStoreAdapter is missing in `transfer.js`. It should be easy to add it though. The easiest workaround is to move the imported files to a `files` directory in your parse-server and configure it to use the parse-server-fs-adapter instead.
```
  "filesAdapter": {
    "module": "parse-server-fs-adapter",
    "options": {
      "filesSubDirectory": ""
    }
```
