### ISSUE TITLE
Processing large number of files - run in parallel or filter out some files?

### ISSUE THREAD

**Issue by joecodespark** [parse-server-modules/parse-files-utils#62]
Does anybody have experience or ideas for speeding up this process? We successfully ran the script on our development server and it processed about 5 files/second. On our live server we have 10 million+ files which at that rate will take 19 days of processing to complete.  So I wonder if there is a fast way to skip some older files (or conditionally based on some other table column) or is it safe to run the script in parallel on multiple hosts? Thanks.

**Comment by BuffMcBigHuge** [comment]
Hey Joe, I was in a similar situation. I decided to write my own version so I got a better idea on what I'm moving, and how long to take. I ironed out all the timeout/memory leaks. Try it out:

https://github.com/BuffMcBigHuge/Mongo-Migrator
