### ISSUE TITLE
ParseError { code: 1, message: undefined }

### ISSUE THREAD

**Issue by sidan5** [parse-server-modules/parse-files-utils#63]
Running this on AWS Elastic Benstalk (single instance) and get this error:

```
Initializing transfer configuration...
Connecting to MongoDB
Successfully connected to MongoDB
Initializing s3 adapter
Fetching schema...
Fetching all objects with files...
ParseError { code: 1, message: undefined }

npm ERR! Linux 4.4.35-33.55.amzn1.x86_64
npm ERR! argv "/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/npm" "start" "config.js"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! parse-files-utils@0.0.1 start: `node index.js "config.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the parse-files-utils@0.0.1 start script 'node index.js "config.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parse-files-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js "config.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parse-files-utils
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls parse-files-utils
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/app/current/npm-debug.log
```

**Comment by KasperLorentzen** [comment]
fixed same error by using https://api.parse.com/1 instead of http://api.parse.com/1

**Comment by sidan5** [comment]
@KasperLorentzen Where do you use that? Shouldn't I use my custom server URL on `serverURL`?

**Comment by KasperLorentzen** [comment]
Well when I said I got it to work I must have messed something else up since all the actual urls are wrong now ... but I got it to run by changing to https. 
I assumed you used the url of the server containing the files, and it did move my files to my S3 bucket it just made all the urls to the parse server and not the bucket.

**Comment by sidan5** [comment]
@KasperLorentzen So what should I fill in serverURL? In case I want to move files to my S3 from Parse hosted server?

**Comment by sidan5** [comment]
@KasperLorentzen with Parse Hosted server URL if shows this error:

`ParseError { code: 11, message: 'your Mongo database is unavailable' }`

**Comment by KasperLorentzen** [comment]
Well that is a good question, I used the parse server url (with https) the error went away and all my files got moved to my bucket, now my parse server have somehow still messed up the urls ...

**Comment by KasperLorentzen** [comment]
Well that error indicates you don't have the right string to your mongoDB URI. It should look like something like this: mongodb://<dbuser>:<dbpassword>@<yourstuff>.mlab.com:XXXX/databasename

**Comment by sidan5** [comment]
@KasperLorentzen On previous config you can see it is successfully connected to MongoDB so it's not the case (it's the exact line I use for my server...

Guess it's something with serverURL that should be the new parse (custom hosted) server. I'll try without https...

**Comment by sidan5** [comment]
@KasperLorentzen Looks like it is working without using https...

Hope it does the work well and not just copying :)
