### ISSUE TITLE
Unable to import 

### ISSUE THREAD

**Issue by wooknight** [parse-server-modules/parse-files-utils#66]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start',
1 verbose cli   'config.js' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle parse-files-utils@0.0.1~prestart: parse-files-utils@0.0.1
6 silly lifecycle parse-files-utils@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle parse-files-utils@0.0.1~start: parse-files-utils@0.0.1
8 verbose lifecycle parse-files-utils@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle parse-files-utils@0.0.1~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Applications/MAMP/htdocs/parse-files-utils/node_modules/.bin:/Users/ramesh/.rbenv/shims:/Users/ramesh/.rbenv/bin:/Applications/MAMP/htdocs/liveTrailREST:/usr/local/php5/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/ramesh/pear/bin:/Users/ramesh/pear/share/pear/PHPUnit:/Users/ramesh/pear/share/pear/:.:~/Documents/utilities/random:
10 verbose lifecycle parse-files-utils@0.0.1~start: CWD: /Applications/MAMP/htdocs/parse-files-utils
11 silly lifecycle parse-files-utils@0.0.1~start: Args: [ '-c', 'node index.js "config.js"' ]
12 silly lifecycle parse-files-utils@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle parse-files-utils@0.0.1~start: Failed to exec start script
14 verbose stack Error: parse-files-utils@0.0.1 start: `node index.js "config.js"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid parse-files-utils@0.0.1
16 verbose cwd /Applications/MAMP/htdocs/parse-files-utils
17 error Darwin 16.3.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "config.js"
19 error node v7.4.0
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error parse-files-utils@0.0.1 start: `node index.js "config.js"`
22 error Exit status 1
23 error Failed at the parse-files-utils@0.0.1 start script 'node index.js "config.js"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the parse-files-utils package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index.js "config.js"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs parse-files-utils
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls parse-files-utils
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by wooknight** [comment]
Processing 613 files
Saving files with filesystem
{ Error: getaddrinfo ENOTFOUND files.parsetfss.com files.parsetfss.com:80
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'files.parsetfss.com',
  host: 'files.parsetfss.com',
  port: 80 }

**Comment by dbarabander** [comment]
@wooknight https://github.com/parse-server-modules/parse-files-utils/pull/67

**Comment by wooknight** [comment]
@dbarabander  Thanks a bunch. You guys rock!!
